---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tsidp
  namespace: tsidp
spec:
  itemPath: "vaults/4kbytax7eoweefgrkbg2af6oxu/items/bxmemgdiqyqfac4fp27ad4jyci"
