---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tailscale
  namespace: tailscale
spec:
  itemPath: "vaults/4kbytax7eoweefgrkbg2af6oxu/items/qr2sdpujkk472inse7whpgvg34"
