---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-cloud-prometheus-auth
  namespace: vertical-pod-autoscaler
spec:
  itemPath: vaults/4kbytax7eoweefgrkbg2af6oxu/items/6242c3k5pndvdzl4psyiphjomm
