---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-proxy
  namespace: vpa
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: GRAFANA_CLOUD_PROM_URL
              value: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom"
            - name: GRAFANA_CLOUD_BASIC_AUTH
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-prometheus-auth
                  key: metrics-proxy-basic-auth
