---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: grafana
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s-monitoring
      version: "^3.7.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  # install:
  #   remediation:
  #     retries: 3
  # interval: 10m
  # upgrade:
  #   cleanupOnFail: true
  #   remediation:
  #     retries: 3
  values:
    cluster:
      name: my-cluster
    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom/push
        auth:
          type: basic
          usernameKey: metrics-username
          passwordKey: credential
        secret:
          create: false
          name: grafana-access-policy-token
          namespace: grafana
      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-012.grafana.net./loki/api/v1/push
        auth:
          type: basic
          usernameKey: logs-username
          passwordKey: credential
        secret:
          create: false
          name: grafana-access-policy-token
          namespace: grafana
    clusterMetrics:
      enabled: true
      kepler:
        enabled: true
    clusterEvents:
      enabled: true
    podLogs:
      enabled: true
    integrations:
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-singleton
                - alloy-logs
    alloy-metrics:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-logs:
      enabled: true
