---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: home-ingress
spec:
  type: ingress
  replicas: 2
  hostnamePrefix: home-ingress
  tags:
    - tag:k8s-service
