---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: shared-ingress
spec:
  type: ingress
  replicas: 2
  hostnamePrefix: shared-ingress
  tags:
    - tag:k8s-shared
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: private-ingress
spec:
  type: ingress
  replicas: 1
  hostnamePrefix: private-ingress
  tags:
    - tag:k8s-private
